/// Curated reference data used to turn free-text vehicle fields into
/// pick-first inputs (bloc 3). Every list is deliberately extensible and
/// every picker built on top of it still allows free text, since no static
/// list can cover every make/model - Principe 7: never block the user on
/// data we don't have.
const List<String> carBrands = [
  'Alfa Romeo',
  'Audi',
  'BMW',
  'BYD',
  'Chery',
  'Chevrolet',
  'Citroën',
  'Cupra',
  'Dacia',
  'Daewoo',
  'DFSK',
  'Dodge',
  'DS Automobiles',
  'Fiat',
  'Ford',
  'Geely',
  'GMC',
  'Honda',
  'Hyundai',
  'Isuzu',
  'Jaguar',
  'Jeep',
  'Kia',
  'Land Rover',
  'Lexus',
  'Mazda',
  'Mercedes-Benz',
  'MG',
  'Mini',
  'Mitsubishi',
  'Nissan',
  'Opel',
  'Peugeot',
  'Porsche',
  'Renault',
  'Seat',
  'Škoda',
  'Smart',
  'SsangYong',
  'Subaru',
  'Suzuki',
  'Tesla',
  'Toyota',
  'Volkswagen',
  'Volvo',
];

/// Common models per brand, offered as suggestions once a brand is picked.
/// Not exhaustive by design - the model field always accepts free text too.
const Map<String, List<String>> carModelsByBrand = {
  'Audi': ['A1', 'A3', 'A4', 'A5', 'A6', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron'],
  'BMW': ['Série 1', 'Série 2', 'Série 3', 'Série 4', 'Série 5', 'X1', 'X2', 'X3', 'X5', 'X6'],
  'Citroën': ['C3', 'C3 Aircross', 'C4', 'C4 Picasso', 'C5 Aircross', 'Berlingo', 'Jumpy'],
  'Dacia': ['Sandero', 'Logan', 'Duster', 'Spring', 'Jogger', 'Lodgy', 'Dokker'],
  'Fiat': ['500', '500X', 'Panda', 'Tipo', 'Doblo', 'Punto'],
  'Ford': ['Fiesta', 'Focus', 'Puma', 'Kuga', 'EcoSport', 'Transit'],
  'Honda': ['Civic', 'CR-V', 'HR-V', 'Jazz', 'Accord'],
  'Hyundai': ['i10', 'i20', 'i30', 'Tucson', 'Santa Fe', 'Kona', 'Accent'],
  'Jeep': ['Renegade', 'Compass', 'Cherokee', 'Wrangler'],
  'Kia': ['Picanto', 'Rio', 'Ceed', 'Sportage', 'Sorento', 'Stonic'],
  'Mazda': ['Mazda2', 'Mazda3', 'CX-3', 'CX-5', 'CX-30'],
  'Mercedes-Benz': ['Classe A', 'Classe B', 'Classe C', 'Classe E', 'GLA', 'GLC', 'GLE'],
  'Nissan': ['Micra', 'Juke', 'Qashqai', 'X-Trail', 'Navara'],
  'Opel': ['Corsa', 'Astra', 'Crossland', 'Grandland', 'Mokka'],
  'Peugeot': ['108', '208', '2008', '308', '3008', '5008', 'Partner'],
  'Renault': ['Clio', 'Captur', 'Mégane', 'Kadjar', 'Scénic', 'Talisman', 'Kangoo'],
  'Seat': ['Ibiza', 'Leon', 'Arona', 'Ateca'],
  'Škoda': ['Fabia', 'Octavia', 'Kamiq', 'Karoq', 'Kodiaq'],
  'Suzuki': ['Swift', 'Vitara', 'S-Cross', 'Jimny'],
  'Toyota': ['Yaris', 'Corolla', 'C-HR', 'RAV4', 'Land Cruiser', 'Hilux'],
  'Volkswagen': ['Polo', 'Golf', 'Passat', 'T-Roc', 'Tiguan', 'Touareg', 'Caddy'],
  'Volvo': ['XC40', 'XC60', 'XC90', 'S60', 'V60'],
};

const List<String> transmissionTypes = ['Automatique', 'Manuelle', 'Autre'];
