/// Extensible list of operation categories (bloc 5, §8.2).
const List<String> maintenanceCategories = [
  'Vidange',
  'Vidange + filtres',
  'Révision',
  'Révision constructeur',
  'Filtre à huile',
  'Filtre à air',
  'Filtre habitacle',
  'Filtre carburant',
  'Plaquettes de frein',
  'Disques de frein',
  'Freinage',
  'Batterie',
  'Bougies',
  'Courroie de distribution',
  'Chaîne de distribution',
  'Courroie accessoires',
  'Embrayage',
  'Pneus',
  'Suspension',
  'Climatisation',
  'Contrôle / diagnostic',
  'Réparation moteur',
  'Réparation électrique',
  'Carrosserie',
  'Réparation',
  'Autre',
];
